# Generated by Django 3.0.5 on 2023-05-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_newmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newmodel',
        ),
    ]
