# Generated by Django 3.0.5 on 2023-05-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_subanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subanswer',
            old_name='rigth_choice',
            new_name='right_choice',
        ),
    ]
